# Generated by Django 5.2.8 on 2026-08-06 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='forks',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='visibility',
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
