# Generated by Django 5.2.8 on 2026-08-12 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_tag_alter_repository_options_repository_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['owner', 'is_public'], name='repos_repos_owner_i_e21404_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['name'], name='repos_repos_name_802af2_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['-created_at'], name='repos_repos_created_1835a1_idx'),
        ),
    ]
